import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

/**
 * Edge Function: send-seo-digest
 *
 * Emails the weekly SEO/GEO digest (generated by scripts/generateSeoDigest.mjs)
 * via Resend. Invoked from the weekly-seo-digest GitHub Action with the digest
 * HTML in the request body. See ADR-0018.
 *
 * Auth: caller must present the service role key as a Bearer token.
 * Body: { subject: string, html: string, to: string }
 */

serve(async (req) => {
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  // Only the GitHub Action (which holds the service role key) may invoke this.
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  const auth = req.headers.get("Authorization") || "";
  if (!serviceRoleKey || auth !== `Bearer ${serviceRoleKey}`) {
    return new Response("Unauthorized", { status: 401 });
  }

  try {
    const { subject, html, to } = await req.json();
    if (!html || !to) {
      throw new Error("Missing 'html' or 'to' in request body");
    }

    const resendApiKey = Deno.env.get("RESEND_API_KEY");
    if (!resendApiKey) {
      throw new Error("RESEND_API_KEY not configured");
    }

    const emailResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "Mystery Maker Insights <noreply@mysterymaker.party>",
        to: [to],
        subject: subject || "Weekly SEO/GEO digest — mysterymaker.party",
        html,
      }),
    });

    if (!emailResponse.ok) {
      const errorText = await emailResponse.text();
      throw new Error(`Resend API error: ${emailResponse.status} ${errorText}`);
    }

    console.log(`SEO digest emailed to ${to}`);
    return new Response(JSON.stringify({ success: true }), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error sending SEO digest:", error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
});
