export interface Message {
  id: string;
  content: string;
  is_ai: boolean;
  timestamp: Date;
  role?: string; // Add optional role property
  isAutoGenerated?: boolean; // Add the missing isAutoGenerated property
}

export interface FormValues {
  title?: string;
  theme?: string;
  numberOfGuests?: number;
  playerCount?: number;
  timeFrame?: string;
  scriptType?: 'full' | 'pointForm'; // Changed back to match the expected type
  mysteryType?: 'murder' | 'intrigue';
  additionalDetails?: string;
  [key: string]: any;
}

export interface QuestionOption {
  target: string;
  question: string;
}

export interface CharacterScript {
  introduction?: string;
  round1?: {
    innocent?: string;
    guilty?: string;
  };
  round2?: {
    innocent?: string;
    guilty?: string;
  };
  round3?: {
    innocent?: string;
    guilty?: string;
  };
  final?: {
    innocent?: string;
    guilty?: string;
  };
}

// Add more detailed interfaces for character details
export interface CharacterWhereabouts {
  location: string;
  details: string;
  witnesses?: string;
  timeGap?: string;
}

export interface CharacterRelationship {
  character: string;
  description: string;
}

export interface CharacterSecret {
  content: string;
}

// Add the more detailed script structure
export interface RoundScript {
  innocent: string;
  guilty: string;
}

export interface CharacterRoundScripts {
  introduction?: string;
  round1?: string | RoundScript;
  round2?: string | RoundScript;
  round3?: string | RoundScript;
  final?: RoundScript;
}